#!/bin/sh
##########################################################
#
# Corescript v1.0 | dependencies
# Last Modified: 30/06/2017
#
##########################################################



#please update ur distro after of the installation.
#for more information go to https://github.com/d43M0n23/corescript/wiki/Requisites 



# USE 
# sudo apt-get update
# sudo apt-get upgrade

if ! hash aircrack-ng 2>/dev/null; then sudo apt-get install --yes aircrack-ng ; fi
if ! hash nmap 2>/dev/null; then sudo apt-get install --yes nmap ; fi
if ! hash apache2 2>/dev/null; then sudo apt-get install --yes apache2 php5 libapache2-mod-php5 ; fi
if ! hash ettercap 2>/dev/null; then sudo apt-get install --yes ettercap-text-only ; fi
if ! hash dhcpd 2>/dev/null; then sudo apt-get install --yes isc-dhcp-server ; fi
if ! hash hostapd 2>/dev/null; then sudo apt-get install --yes hostapd ; fi
if ! hash arpspoof 2>/dev/null; then sudo apt-get install --yes arpspoof ; fi
if ! hash dnsspoof 2>/dev/null; then sudo apt-get install --yes dnsspoof ; fi
if ! hash xterm 2>/dev/null; then sudo apt-get install --yes xterm ; fi
if ! hash default-jre 2>/dev/null; then sudo apt-get install --yes default-jre ; fi
