#!/bin/bash
### BEGIN INIT INFO
# Provides:          d43M0n23_update
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Should-Start:      $portmap
# Should-Stop:       $portmap
# X-Start-Before:    nis
# X-Stop-After:      nis
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO



#startscript daemon23_update
#update-rc.d DIENSTNAME defaults 80 10
#update-rc.d -f d43M0n23_update remove && update-rc.d -f d43M0n23_update defaults && update-rc.d -f d43M0n23_update enable


case "$1" in
start)
	/root/./d43M0n23_update &
	echo "$!" > /tmp/d43M0n23_update_pid
	echo "d43M0n23_update wurde gestartet..."
	;;
stop)
	kill -9 /tmp/d43M0n23_pid
	echo "d43M0n23_update wurde gestopt..."
	;;
restart)
	$0 stop
	$0 start
	echo "d43M0n23_update wurde restartet..."
	;;
*)
	echo "Falsche Benutzung, bitte $0 (start|stop|restart)"
	exit 1
	;;
esac
exit 0
